### ISSUE TITLE
UPDATE fails to update target langs

### ISSUE THREAD

**Issue by srl295** [IBM-Bluemix/gp-deliverypipeline#21]
for both `.properties` and `.json`, the UPDATE phase does not modify the target language set. (CREATE sets it properly).

This causes problems on update if the target langs changed.
 
Workaround: delete the project before running

**Comment by srl295** [comment]
so actually, I am not sure about the purpose of `-r UPDATE` at this point. @jgarcows ? @rjminsha ? 

more important for now is that `-r CREATE` updates the target languages if they are wrong. It could probably just always do an update before upload, which might be a no-op.

**Comment by srl295** [comment]
blocked by https://github.com/IBM-Bluemix/gp-java-tools/issues/49 as there's no way to actually do this with gp-cli short of delete/recreate.
//cc @yumaoka

**Comment by steveatkin** [comment]
Do you think we can quickly get an update feature into the gp-cli quickly? We cannot use the delete/recreate approach as someone may have made edits and we would end up deleting them.
